# Generated by Django 4.0.8 on 2022-11-26 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=13, null=True)),
                ('country_code', models.CharField(max_length=4, null=True)),
                ('name', models.CharField(max_length=30, null=True)),
                ('email', models.EmailField(max_length=255)),
                ('is_registered', models.BooleanField(default=False)),
                ('is_personal_contact', models.BooleanField(default=False)),
                ('is_marked_as_spam', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['id', 'name', 'is_registered', 'phone_number', 'country_code', 'email', 'is_personal_contact', 'is_marked_as_spam'],
            },
        ),
        migrations.CreateModel(
            name='SpamDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marked_at', models.DateTimeField(auto_now_add=True)),
                ('marked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Spam2Global', to='users.globaldb')),
                ('spam_phone_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Global2Spam', to='users.globaldb')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact_of', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Personal2Global', to='users.globaldb')),
                ('personal_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Global2Personal', to='users.globaldb')),
            ],
        ),
    ]
