# Generated by Django 4.0.8 on 2022-11-26 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globaldb',
            name='email',
            field=models.EmailField(blank=True, max_length=255),
        ),
    ]
