# Generated by Django 4.0.8 on 2022-11-26 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_globaldb_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalcontact',
            name='personal_contact',
        ),
        migrations.AddField(
            model_name='personalcontact',
            name='country_code',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='personalcontact',
            name='phone_number',
            field=models.CharField(max_length=13, null=True),
        ),
    ]
