# Generated by Django 4.0.8 on 2022-11-26 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_personalcontact_personal_contact_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spamdb',
            name='spam_phone_number',
        ),
        migrations.AddField(
            model_name='spamdb',
            name='country_code',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='spamdb',
            name='phone_number',
            field=models.CharField(max_length=13, null=True),
        ),
    ]
